src/Entity/Transferts.php
<?php

namespace App\Entity;

use App\Repository\TransfertsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TransfertsRepository::class)
 */
class Transferts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\ManyToOne(targetEntity=Accounts::class, inversedBy="transferts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Accounts;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_transfert;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getAccounts(): ?Accounts
    {
        return $this->Accounts;
    }

    public function setAccounts(?Accounts $Accounts): self
    {
        $this->Accounts = $Accounts;

        return $this;
    }

    public function getDateTransfert(): ?\DateTimeInterface
    {
        return $this->date_transfert;
    }

    public function setDateTransfert(\DateTimeInterface $date_transfert): self
    {
        $this->date_transfert = $date_transfert;

        return $this;
    }
}

templates/particulier/mes-contact.html.twig
{% extends 'base.html.twig' %}

{# TitlePage #}
{% block title %}
	AdaLovelace - Equipe
{% endblock %}
{# ./TitlePage #}

{# stylessheetForDashboard #}
{% block stylesheets %}<link rel="stylesheet" href="{{ asset('css/teams.css') }}">
{% endblock %}
{# ./stylessheetForDashboard #}

{# navBarTop #}
{% block nav %}

	<nav class="navbar fixed-top navbar-expand-lg navbar-light shadow bg-white">
		<a class="navbar-brand text-dark" href="{{ path ("app_accueil") }}">ADALOVELACE</a>

		{# collapse navbar #}
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeaderToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
			<span class="btn btn-light">MENU</span>
		</button>
		{# ./collapse navbar #}

		<div
			class="collapse navbar-collapse justify-content-end" id="navbarHeaderToggler">

			{# ul navbar #}
			<ul class="nav mx-5">
				<li class="nav-item active">
					<a class="nav-link text-dark" href="{{ path ("app_accueil") }}">Accueil<span class="sr-only">(current)</span>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" href="{{ path ("app_actualite") }}">Actualités</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" href="{{ path ("app_equipe") }}" tabindex="-1" aria-disabled="true">Nos Equipes</a>
				</li>
			</ul>
			{# ./ul navbar #}

			{# Login Logout #}
			{% if is_granted('IS_AUTHENTICATED_FULLY') %}
				<a href="{{path('particulier_mon-espace')}}" class="btn btn-sm text-white btn-success shadow m-2 my-sm-0">Mon Espace</a>
				<a href="{{path('app_logout')}}" class="btn btn-sm btn-danger shadow m-2 my-sm-0">Deconnexion</a>
			{% else %}
				<a href="{{ path ("app_login") }}" class="btn btn-sm btn-primary text-white shadow m-2 my-sm-0" type="button">Mon Espace</a>
			{% endif %}
			{# ./Login Logout #}

		</div>
	</nav>

{% endblock %}
{# ./navBarTop #}

{% block main %}

	<!-- Team -->
	<section id="team" class="pb-5">
		<div class="container">
			<h4 class="card section-title text-dark shadow py-4">Notre Equipe</h4>
			<div
				class="row">
				<!-- Team member -->
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="image-flip">
						<div class="mainflip flip-0">
							<div class="frontside">
								<div class="card shadow">
									<div class="card-body text-center">
										<p><img class="img-fluid " src="https://avatars0.githubusercontent.com/u/67335568?s=400&u=ac5f6481217fb26a07edabe5856986caafbd5e19&v=4" alt="card image"></p>
										<h4 class="card-title text-danger">Baptiste.C</h4>
										<p class="card-text">Lead-Dev-Junior.</p>
										<a href="#" class="btn btn-danger btn-sm shadow">
											<i class="fa fa-eye"></i>
										</a>
									</div>
								</div>
							</div>
							<div class="backside">
								<div class="card shadow">
									<div class="card-body text-center mt-4" style="width: 540px;">
										<h4 class="card-title text-danger">Baptiste.C</h4>
										<p class="card-text">Jeune Lead Dev, spécialisé back-end.<br><br>
											<span class="font-weight-light font-italic">"Du côté obscur de la force"</span>
										</p>
										<ul class="list-inline">
											<li class="list-inline-item">
												<a class="social-icon text-xs-center text-danger text-danger" target="_blank" href="#">
													<i class="fa fa-facebook"></i>
												</a>
											</li>
											<li class="list-inline-item">
												<a class="social-icon text-xs-center text-danger" target="_blank" href="#">
													<i class="fa fa-twitter"></i>
												</a>
											</li>
											<li class="list-inline-item">
												<a class="social-icon text-xs-center text-danger" target="_blank" href="#">
													<i class="fa fa-skype"></i>
												</a>
											</li>
											<li class="list-inline-item">
												<a class="social-icon text-xs-center text-danger" target="_blank" href="#">
													<i class="fa fa-google"></i>
												</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- ./Team member -->
				<!-- Team member -->
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="image-flip" ontouchstart="this.classList.toggle('hover');">
						<div class="mainflip">
							<div class="frontside">
								<div class="card shadow">
									<div class="card-body text-center">
										<p><img class=" img-fluid" src="http://pngwebicons.com/uploads/anime/ico/anime_icon6679.ico" alt="card image"></p>
										<h4 class="card-title text-success">Duchaîne.KDD</h4>
										<p class="card-text">Dev Junior.</p>
										<a href="#" class="btn btn-success btn-sm shadow">
											<i class="fa fa-eye"></i>
										</a>
									</div>
								</div>
							</div>
							<div class="backside">
								<div class="card">
									<div class="card-body text-center mt-4" style="width: 540px;">
										<h4 class="card-title text-success">Duchaîne.KDD</h4>
										<p class="card-text">Dev Junior en formation.<br><br>
											<span class="font-weight-light font-italic">"Du côté lumineux de la force"</span>
										</p>
										<ul class="list-inline">
											<li class="list-inline-item">
												<a class="social-icon text-xs-center text-success" target="_blank" href="#">
													<i class="fa fa-facebook"></i>
												</a>
											</li>
											<li class="list-inline-item">
												<a class="social-icon text-xs-center text-success" target="_blank" href="#">
													<i class="fa fa-twitter"></i>
												</a>
											</li>
											<li class="list-inline-item">
												<a class="social-icon text-xs-center text-success" target="_blank" href="#">
													<i class="fa fa-skype"></i>
												</a>
											</li>
											<li class="list-inline-item">
												<a class="social-icon text-xs-center text-success" target="_blank" href="#">
													<i class="fa fa-google"></i>
												</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- ./Team member -->
			</div>
		</div>
	</section>
	<!-- Team -->

{% endblock %}

templates/particulier/mon-compte.html.twig
{% extends 'base.html.twig' %}

{# Title Page #}
{% block title %}
	AdaLovelace -
	{{account.AccountType.name}}
{% endblock %}
{# ./Title Page #}

{# stylessheets Dashboard #}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('css/user.css') }}">
{% endblock %}
{# ./stylessheets Dashboard #}

{# navBarTop #}
{% block nav %}
	{% include "template-elem/userDash/navTop.html.twig" %}
{% endblock %}
{# ./navBarTop #}

{# header !! dont delete !! #}
{% block header %}{% endblock %}
{# ./header !! dont delete !! #}

{# Main content #}
{% block main %}

	<main
		class="wrapper">

		{# sideNavBar #}
		{% include "template-elem/userDash/sideBarNav.html.twig" %}
		{# sideNavBar #}

		{# page name #}
			<div class="content"> <div class="row">
				<div class="container-fluid text-dark text-center mx-5 p-0">
					<div class="col-2 card mx-4 mt-5">
						<h5 class="p-2">Mon {{account.AccountType.name}}</h5>
					</div>
				</div>
			</div>
			{# ./page name #}

			<div class="row">
					<div class="container-fluid d-flex flex-wrap justify-content-center mx-2 my-5">
						<div
							class="col-lg-7 card text-white shadow mb-5 rounded p-0">

							{# account title #}
							<div class="card-header text-center shadow">
								<h5 class="text-dark">
									{{account.AccountType.name}}
									- numéro : {{account.id}}
								</h5>
							</div>
							{# ./account title #}

							{# account amount #}
							<div class="card bg-lightGrey mx-auto mt-3 mb-3 mt-5">
								<h5 class="card-title text-dark font-weight-bold m-1 p-2">
									Solde :
									{{account.amount}}<span class="text-warning">€</span>
								</h5>
							</div>
							{# ./account amount #}

							{# Transfert operation #}
							{% for transfert in account.transferts|slice(- 1) %}
								<div class="card-body text-dark">
									<div class="d-flex flex-column align-items-center">
										<div class="d-flex align-items-center">
											<div class="mt-2">
												<p class="card-title">Nom du débit ou du crédit.</p>
											</div>
											<div class="">
												<p class="card-title m-0 p-0">
													<span class="bg-white">|</span>
													<span class="font-weight-bold">
														{% if (transfert.type == 0 )%}
															<span class="text-danger font-weight-bold">-</span>
														{% else %}
															<span class="text-success font-weight-bold">+</span>
														{% endif %}
													</span>
													<span class="font-weight-bold">{{transfert.amount}}</span>
													<span class="text-warning">€</span>
												</p>
											</div>
										</div>
									</div>
								</div>
							{% endfor %}
							{# ./Transfert operaton #}

							<div
								class="card-footer text-center">
							{# delete account #}
							<a class="btn btn-danger shadow" href="">Supprimer mon compte</a>
							{# ./delete account #}

							{# operation account #}
							<a class="btn btn-success shadow" href="{{ path ("particulier_transfert", {id:account.id}) }}">Faire un virement</a>
							{# ./operation account #}
							</div>
						</div>
						{# stats icone account #}
						<div
							class="col-lg-4 text-black mb-5 mx-2 rounded">
							{# <img src="" alt=""> #}
							<div class="row d-flex flex-wrap">
								<div class="col-4 card text-center p-0 mx-2" style="width: 40px; height: 100%">
									<h6 class="card-header">Calendrier</h6>
									<a href="">
										<img class="my-4" src="https://www.graphicsfuel.com/wp-content/uploads/2012/02/calendar-icon-512x512.png" alt="" style="width: 80px; height: 80px">
									</a>
								</div>
								<div class="col-4 card text-center p-0 mx-2" style="width: 40px; height: 100%">
									<h6 class="card-header">Statistiques</h6>
									<a href="">
										<img class="my-4" src="https://www.psdgraphics.com/file/money-icon.jpg" alt="" style="width: 80px; height: 80px">
									</a>
								</div>
								<div class="col-4 card text-center p-0 mx-2 mt-3" style="width: 40px; height: 100%">
									<h6 class="card-header">Devise</h6>
									<a href="">
										<img class="my-4" src="https://www.psdgraphics.com/wp-content/uploads/2009/05/euro-symbol.jpg" alt="" style="width: 80px; height: 80px">
									</a>
								</div>
								<div class="col-4 card text-center p-0 mx-2 mt-3" style="width: 40px; height: 100%">
									<h6 class="card-header">Coffre</h6>
									<a href="">
										<img class="my-4" src="https://www.psdgraphics.com/file/gold-bars-png.png" alt="" style="width: 80px; height: 80px">
									</a>
								</div>
							</div>
						</div>
						{# ./stats icone account #}
					</div>

				</div>
			</div>
			{# ./Account #}
		</div>
	</main>
	{# ./Main content #}
{% endblock %}

{# footer !! dont delete !! #}
{% block footer %}{% endblock %}
{# ./footer !! dont delete !! #}

templates/particulier/mon-espace.html.twig
{% extends 'base.html.twig' %}

{# Title Page #}
{% block title %}
	Mon Espace
{% endblock %}
{# ./Title Page #}

{% block stylesheets %}{% endblock %}

{# navBarTop #}
{% block nav %}
	{% include "template-elem/userDash/navTop.html.twig" %}
{% endblock %}
{# ./navBarTop #}

{# header !! dont delete !! #}
{% block header %}{% endblock %}
{# ./header !! dont delete !! #}

{# main Content #}
{% block main %}

	<main>
		{# sideNavBar #}
		{% include "template-elem/userDash/sideBarNav.html.twig" %}
		{# ./sideNavBar #}

		{# page name #}
			<div class="content"> <div class="row">
				<div class="container-fluid text-dark text-center mx-5 p-0">
					<div class="col-2 card mx-4 mt-5">
						<h5 class="p-2">Mon Espace</h5>
					</div>
				</div>
			</div>
			{# ./page name #}

			<div class="row">
				{% for account in app.user.accounts  %}
					<div class="container-fluid d-flex flex-wrap justify-content-center mx-2 my-5">
						<div
							class="col-lg-7 card text-white shadow mb-5 rounded p-0">

							{# account title #}
							<div class="card-header text-center shadow">
								<h5 class="text-dark">
									{{account.AccountType.name}}
									- numéro : {{account.id}}
								</h5>
							</div>
							{# ./account title #}

							{# account amount #}
							<div class="card bg-lightGrey mx-auto mt-3 mb-3 mt-5">
								<h5 class="card-title text-dark font-weight-bold m-1 p-2">
									Solde :
									{{account.amount}}<span class="text-warning">€</span>
								</h5>
							</div>
							{# ./account amount #}

							{# Transfert operation #}
							{% for transfert in account.transferts|slice(- 1) %}
								<div class="card-body text-dark">
									<div class="d-flex flex-column align-items-center">
										<div class="d-flex align-items-center">
											<div class="mt-2">
												<p class="card-title">Nom du débit ou du crédit.</p>
											</div>
											<div class="">
												<p class="card-title m-0 p-0">
													<span class="bg-white">|</span>
													<span class="font-weight-bold">
														{% if (transfert.type == 0 )%}
															<span class="text-danger font-weight-bold">-</span>
														{% else %}
															<span class="text-success font-weight-bold">+</span>
														{% endif %}
													</span>
													<span class="font-weight-bold">{{transfert.amount}}</span>
													<span class="text-warning">€</span>
												</p>
											</div>
										</div>
									</div>
								</div>
							{% endfor %}
							{# ./Transfert operaton #}

							<div
								class="card-footer text-center">
								{# show account #}
								<a class="btn btn-info shadow" href="{{ path ('particulier_mon-compte', {id:account.id}) }}">Visualiser mon compte</a>
								{# ./show account #}
							</div>
						</div>

						{# stats icone account #}
						<div
							class="col-lg-4 text-black mb-5 mx-2 rounded">
							{# <img src="" alt=""> #}
							<div class="row d-flex flex-wrap">
								<div class="col-4 card text-center p-0 mx-2" style="width: 40px; height: 100%">
									<h6 class="card-header">Calendrier</h6>
									<a href="">
										<img class="my-4" src="https://www.graphicsfuel.com/wp-content/uploads/2012/02/calendar-icon-512x512.png" alt="" style="width: 80px; height: 80px">
									</a>
								</div>
								<div class="col-4 card text-center p-0 mx-2" style="width: 40px; height: 100%">
									<h6 class="card-header">Statistiques</h6>
									<a href="">
										<img class="my-4" src="https://www.psdgraphics.com/file/money-icon.jpg" alt="" style="width: 80px; height: 80px">
									</a>
								</div>
								<div class="col-4 card text-center p-0 mx-2 mt-3" style="width: 40px; height: 100%">
									<h6 class="card-header">Devise</h6>
									<a href="">
										<img class="my-4" src="https://www.psdgraphics.com/wp-content/uploads/2009/05/euro-symbol.jpg" alt="" style="width: 80px; height: 80px">
									</a>
								</div>
								<div class="col-4 card text-center p-0 mx-2 mt-3" style="width: 40px; height: 100%">
									<h6 class="card-header">Coffre</h6>
									<a href="">
										<img class="my-4" src="https://www.psdgraphics.com/file/gold-bars-png.png" alt="" style="width: 80px; height: 80px">
									</a>
								</div>
							</div>
						</div>
						{# ./stats icone account #}
					</div>
				{% endfor %}
			</div>
		</div>
	</main>
{% endblock %}
{# ./main content #}

{# footer !! dont delete !! #}
{% block footer %}{% endblock %}
{# ./footer !! dont delete !! #}

templates/particulier/mon-identite.html.twig
{% extends 'base.html.twig' %}

{# Title Page #}
{% block title %}
	Mon Identite
{% endblock %}
{# ./Title Page #}

{% block stylesheets %}{% endblock %}

{# navBarTop #}
{% block nav %}
	{% include "template-elem/userDash/navTop.html.twig" %}
{% endblock %}
{# ./navBarTop #}

{# header !! dont delete !! #}
{% block header %}{% endblock %}
{# ./header !! dont delete !! #}

{# main Content #}
{% block main %}

	<main class="col-md-9 ml-sm-auto col-lg-12 px-md-4 mt-5">

		<div class="container">
			<div
				class="row">

				{# page name #}
				<div class="content">
					<div class="row">
						<div class="container-fluid text-dark text-center mx-5 p-0">
							<div class="col-2 card mx-4 mt-5">
								<h5 class="p-2">Mon Identité</h5>
							</div>
						</div>
					</div>
					{# ./page name #}

					<div class="col-sm col-lg-6">
						<h1>IDENTITY</h1>
					</div>
				</div>
			</div>
		</div>
	</main>
{% endblock %}
{# ./main content #}

{# footer !! dont delete !! #}
{% block footer %}{% endblock %}
{# ./footer !! dont delete !! #}

templates/particulier/ouvrir-un-compte.html.twig
{% extends 'base.html.twig' %}

{# TitlePage #}
{% block title %}
	AdaLovelace - Nouveau Compte
{% endblock %}
{# ./TitlePage #}

{# stylessheetForDashboard #}
{% block stylesheets %}<link rel="stylesheet" href="{{ asset('css/user.css') }}">
{% endblock %}
{# ./stylessheetForDashboard #}

{# navBarTop #}
{% block nav %}
	{% include "template-elem/userDash/navTop.html.twig" %}
{% endblock %}
{# ./navBarTop #}

{# header !! dont delete !! #}
{% block header %}{% endblock %}
{# ./header !! dont delete !! #}

{# Main content #}
{% block main %}

	<main
		class="col-md-9 ml-sm-auto col-lg-12 px-md-4 mt-5">

		{# sideNavBar #}
		{% include "template-elem/userDash/sideBarNav.html.twig" %}
		{# sideNavBar #}

		<div
			class="content">

			{# addAccount Form #}
			<div class="container">
				<div class="row">
					<div class="container-fluid text-dark text-center  p-0">
						<div class="col-2 card mt-5">
							<h5 class="p-2">Ouvrir un compte</h5>
						</div>
					</div>
					<div class="col-sm col-lg-6 card text-dark my-5">
						<div class="m-5">
							{{form(form)}}
							</div>
						</div>
					</div>
					{# addAccount Form #}

				</main>
			{% endblock %}
			{# ./Main content #}

			{# footer !! dont delete !! #}
			{% block footer %}{% endblock %}
			{# ./footer !! dont delete !! #}

templates/particulier/transfert.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}<link rel="stylesheet" href="{{ asset('css/user.css') }}">
{% endblock %}

{# navBarTop #}
{% block nav %}
	{% include "template-elem/userDash/navTop.html.twig" %}
{% endblock %}
{# ./navBarTop #}

{% block header %}{% endblock %}


{% block main %}

	<main
		class="col-md-9 ml-sm-auto col-lg-12 px-md-4 mt-5">

		{# sideNavBar #}
		{% include "template-elem/userDash/sideBarNav.html.twig" %}
		{# sideNavBar #}

		{# main Content #}
			<div class="content"> <div class="container">
				<div class="row">
					<div class="container-fluid text-dark text-center  p-0">
						<div class="col-2 card mt-5">
							<h5 class="p-2">Virement</h5>
						</div>
					</div>
					<div class="col-sm col-lg-6 card text-dark mt-5">
						{{form(form)}}
						</div>
					</div>
				</div>
			</main>
		{% endblock %}

		{% block footer %}{% endblock %}